import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { IPFormProvider } from "@/contexts/IPFormContext";
import Navbar from "@/components/Navbar";
import { IPTableProvider } from "@/contexts/IPTableContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "URE IPR Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} antialiased`}>
        <div className='min-h-screen flex flex-col'>
          <IPTableProvider>
            <IPFormProvider>
              <Navbar />
              {children}
            </IPFormProvider>
          </IPTableProvider>
        </div>
      </body>
    </html>
  );
}
